(:name "one-image-between-paragraphs"
 :body "Before\n*\nAfter\n"
 :ops
 (((ty . "is") (s . "Before\n*\nAfter\n"))
  ((ty . "ae") (et . "inline")
   (id . "kix.synthetic-image-one")
   (law . t)
   (epm . ((ee_eo . ((i_cid . "s-blob-v1-IMAGE-synthetic-one")
                     (i_wth . 468.0)
                      (i_ht . 102.0))))))
   ((ty . "te") (id . "kix.synthetic-image-one") (spi . 8)))
 )
