(:name "image-and-literal-asterisk"
 :body "Image\n*\nLiteral\n*\nAfter\n"
 :ops
 (((ty . "is") (s . "Image\n*\nLiteral\n*\nAfter\n"))
  ((ty . "ae") (et . "inline")
   (id . "kix.synthetic-image-mixed")
   (law . t)
   (epm . ((ee_eo . ((i_cid . "s-blob-v1-IMAGE-synthetic-mixed")
                     (i_wth . 468.0)
                     (i_ht . 102.0))))))
  ((ty . "te") (id . "kix.synthetic-image-mixed") (spi . 7)))
 )
